name: CI

on: [pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ruby: [2.7, 3.0, 3.1, head]
    runs-on: ${{ matrix.os }}
    env:
      TREE_SITTER_PARSER_DIR: test/tree-sitter/fixtures/parsers
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake
    - name: CodeCov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage/coverage.xml

